### ISSUE TITLE
Undo button for hidden post

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#117]
Please make the undo button for hidden post.

**Comment by cyh76507707** [comment]
Can you leave the hidden post at the bottom of the list rather than hide from the list? It will be more convenient when we unhide some post.

**Comment by sydneyitguy** [comment]
We shouldn't. 
Because searches & index API meant to be limited on active posts, and we shouldn't waste traffic & server load of inactive posts just for an admin purpose. It also requires an additional UI level post hidden feature for normal users.

Finding a hidden post is easy because we log them on #moderation channel on Discord.
I guess that's easy enough?
