### ISSUE TITLE
Indentation of replies to comments

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#124]
Currently the replies to the comments keep have one more indent. It seems ok in the desktop view, but it looks too much on mobile view when there're too many indents.

I think we can change like ProductHunt with adding a vertical line.
<img width="664" alt="screenshot 2018-05-11 10 52 12" src="https://user-images.githubusercontent.com/15100667/39918927-f5785238-5509-11e8-826b-592af3a40e9a.png">

**Comment by sydneyitguy** [comment]
@cyh76507707 Can you probably put that onto Sketch with some may depth examples?
That vertical line looks better, but it requires more space to the right side of the vertical line -> means less space for text.

I'm not sure how PH solved the problem with so many dpeths. Maybe limit the maximum indentation? but we can't because it's STEEM that has no depth limit.
