### ISSUE TITLE
Better guidelines on what's a "New & Cool" product

### ISSUE THREAD

**Issue by Folken8** [Steemhunt/web#144]
So we need to improve this definition of what's a "New & Cool" product. 
Definition of "cool": 

> A "cool" product is a product that can be common, but with a killer feature. 

Something that makes this product different, even if it's still a common one. 

Definition of "new": 

???

EDIT: 
"killer" can be kinda subjective.

**Comment by Folken8** [comment]
This is the definition on ProductHunt

> Product Hunt is for new or relatively unknown tech products. As much as we love Facebook.com, it probably isn’t a good fit for the homepage today. :)

Source: https://www.producthunt.com/protips

Definition on what's "new" on PH: 


> Can I post something that's been around for a while?
> People visit Product Hunt to discover new things. While most submissions should be for new products, occasionally lesser known hunts are equally loved. Since "new" is subjective, we reserve the right to remove submissions that may be well known within the community.

Source: https://help.producthunt.com/posting/can-i-post-something-thats-been-around-for-a-while

**Comment by cyh76507707** [comment]
A "cool" product must have some "wow effect" by majority of people. Something "cool" can be subjective to everyone. But the meaning of top products in Steemhunt is that those products have a wide range of agreement by hunters who think they are "cool" enough to give some excitement for early adaptors. 

These are examples of "NOT COOL ENOUGH."
- It was cool by majority of people when it was launched, but not anymore because most of people know the product and use it at this point. 
- Only small numbers of people think it is cool.
- Something cliche adj on the products like "Pretty, cute, cheap, easy to use or convenient to use."

**Comment by sydneyitguy** [comment]
@cyh76507707 is this already included in our new posting guidelines?
please close the ticket if it did
