### ISSUE TITLE
Cool-o-meter enhancement 

### ISSUE THREAD

**Issue by Folken8** [Steemhunt/web#154]
This is just an enhancement proposition: 

Add a button only viewable by logged in hunters that ask if a product is cool or not.

Example: 

"Is it cool?" 👍 - 👎

This should be placed next to the upvote button. 

This question is basically just a counter that starts from 0 and can be negative. 

Every time vote 👍 the counter increase +1
Every time vote 👎 the counter decrease -1

The total will be **only viewable** by Moderators and Admins. **The goal is to improve the vision of what is cool and what is not** and also to allow Moderators to reconsider a product already verified or hidden. 

Example: If a product gets barely verified and got a score of -35 after some hours, the moderator could reconsider to hide the product.

**Comment by Folken8** [comment]
Some examples: 
https://www.buenosdeals.com/
https://www.hotukdeals.com/
https://www.pepper.co.kr

**Comment by Chuuuckie** [comment]
Users will still have to upvote the post 50% - 100% (validate increase of vote) .

**Comment by sydneyitguy** [comment]
yeah we've been thinking of similar stuff before.. but we don't think there's a good implementation for this because:

1. We already have upvoting system, another up/down votings can be confusing
2. We thought about some down-voting system as well, but not really down-voting on Steem blockchain, so ppl can still express the opposite opinion. However, this can also be very confusing with Steem down voting system.
