### ISSUE TITLE
Suggestion for Category [Approved Hunts]

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/web#243]
*Please correct me if Im wrong.*

As an influencer, it is convenient to upvote the hunt when it is already approved by the Moderator. It is  because we don't press the (check it out) button because it is the moderators job and decision to delist/approve the hunt. 

What I wanted to suggest is to add an Approved Hunt from the caregory Hunt Score/Random/New etc..

**Comment by sydneyitguy** [comment]
"Check it out" button is just to see the product website, nothing related to moderators

We didn't make "approved" filter or display the review status on the list because we want to minimize the effect of late review disadvantages.

So, you don't need to care whether the posts is approved or not when you're  upvoting.
You don't get any disadvantages by voting on de-listed posts. (You can still get HUNT token distribution for upvoting, and comment upvoting by SH voting bots)
