### ISSUE TITLE
Review comment interface

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#56]
Create a review comment that gives pros and cons of the product.

**Comment by sydneyitguy** [comment]
1. Read comments, and if they have both
"Pros:" and "Cons:" inside the text, put them to the top of the comments.

2. Add switch button on the right top of comment input page
![image](https://user-images.githubusercontent.com/1332279/37328358-4345078c-26dd-11e8-895d-f37572e38ba9.png)

**Comment by cyh76507707** [comment]
We may need to separate our 20% voting pool into hunting posts and pros and cons comments, and weight them separately.

**Comment by cyh76507707** [comment]
If the user switches the button, a template comes out like this:

```
Pros: 
* 
* 

Cons:
*
*
```

**Comment by sydneyitguy** [comment]
With the new rule, we need character count, vote checking, etc

**Comment by cyh76507707** [comment]
[Problems]
So, we designed the review comment to promote some healthy discussions about the products among hunters. However, it becomes just a penny-digging-channel for people to dump meaningless and too many review comments on the hunting post.

[Solution]
- Review comment won't have any format (so, no more pros and cons). All kinds of reviews are possible as an review comment.
- We will make a separate interface for the review comments.
- If the comment is generated via the interface, you will see *[HELPFUL]* button. Hunters can upvote the comment via helpful button. 
- @steemhunt will upvote only upvote the top review comment of the post, and it should have at least one 'helpful' upvotes by hunters to be in the candidates.
- Reviewer must upvote the hunt over 50% vp.
- Reviewer can't self-vote on his review comment.
- Reviewer must be different to the hunter of the post.
- No duplication allowed.
- Minimum length is 80 character or above.

**Comment by Chuuuckie** [comment]
[Problem]

- 100 comments are only upvoted randomly everyday
- Spammers and Abusers still had bigger chances of getting an upvote if it is a lottery system.
- Useless comments owned by spam users are getting an upvote (they still continue to do this)


[Solution] Suggestion only

- Let us not use the thing called "Helpful" Button , it is useless since some will be biased.
Scenario:
If I had 2 accounts that comments every hunt to each other and clicked the successful button.

- Review Comments must also be Qualified for Understanding the Hunt very well.
- Monitoring, Moderating and marking comments manually and may the best comment win based by the moderation team. (The moderator who appoved the post will be the ones to monitor the hunt and its comments)
- 1 or 2 Maximum Comment reviews per upvote. 
Scenario:
200 hunts per day = 1 max comment per hunt 200 - 400 comments will be upvoted . 

If it is still draining, then lets go to 100 comments that only upvotes review hunts top 1 - 100.

- Locked a span of time. (Review only 6 hours after it gets approved) Hunters can only add a review comment after it gets approved.

**Comment by cyh76507707** [comment]
[Adding Evaluation Feature]

1. Innovative (It has definite killer features)
2. New? (I’m sure the majority never seen this)
2. Posting Quality (Title, Desc, Screenshots, Hunter’s comment, Language, Plagiarism…)
3. Uniqueness (It’s not generic at all)
4. Willing to Use (I’m gonna purchase/use/download)
5. ….

Hunters can add the evaluation score together.

Also add ranking system on the review comments on the hunting post.

**Comment by Chuuuckie** [comment]
[SUGGESTION]

I think hunters should not be the one who is going to evaluate the comment review, but instead the moderators. Some comments will be biased.

**Comment by sydneyitguy** [comment]
merged into #221
